"""
DATAVIS v5 ULTIMATE — Supabase Database Connector & Integration Module
---------------------------------------------------------------------
Provides optional cloud database synchronization using Supabase PostgreSQL.
"""

import os
import requests

# Default Supabase Config (Loaded from environment variables or set manually)
SUPABASE_URL = os.getenv("SUPABASE_URL", "")
SUPABASE_KEY = os.getenv("SUPABASE_KEY", "")


def is_supabase_configured():
    return bool(SUPABASE_URL and SUPABASE_KEY)


def get_headers():
    return {
        "apikey": SUPABASE_KEY,
        "Authorization": f"Bearer {SUPABASE_KEY}",
        "Content-Type": "application/json",
        "Prefer": "return=representation"
    }


def sync_user_to_supabase(user_dict: dict) -> bool:
    """Syncs a user account to Supabase 'users' table."""
    if not is_supabase_configured():
        return False
    try:
        url = f"{SUPABASE_URL.rstrip('/')}/rest/v1/users"
        data = {
            "email": user_dict["email"],
            "name": user_dict["name"],
            "turns_remaining": user_dict.get("turns_remaining", 3),
            "total_analyses": user_dict.get("total_analyses", 0),
            "is_paid_tier": bool(user_dict.get("is_paid_tier", False)),
            "role": user_dict.get("role", "user")
        }
        res = requests.post(url, json=data, headers=get_headers())
        return res.status_code in (200, 201)
    except Exception as e:
        print("Supabase sync error:", e)
        return False


def get_supabase_sql_schema():
    """Returns the SQL statements required to initialize Supabase PostgreSQL tables."""
    return """
-- ============================================================
-- SUPABASE SQL SCHEMA FOR DATAVIS v5 ULTIMATE
-- Paste this into Supabase SQL Editor (https://supabase.com)
-- ============================================================

CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    turns_remaining INT DEFAULT 3,
    total_analyses INT DEFAULT 0,
    is_paid_tier BOOLEAN DEFAULT FALSE,
    role TEXT DEFAULT 'user',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.analyses_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id),
    analysis_type TEXT NOT NULL,
    dataset_info TEXT,
    files_count INT DEFAULT 1,
    extra_files_fee NUMERIC DEFAULT 0,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id),
    amount_inr NUMERIC NOT NULL,
    turns_added INT NOT NULL,
    payment_method TEXT DEFAULT 'GPay / UPI',
    utr_number TEXT NOT NULL,
    status TEXT DEFAULT 'APPROVED',
    timestamp TIMESTAMPTZ DEFAULT NOW()
);
"""
